export const USER_SIGNIN_LOADING = 'USER_SIGNIN_LOADING';
export const USER_SIGNIN_SUCCESS = 'USER_SIGNIN_SUCCESS';
export const USER_SIGNIN_ERROR = 'USER_SIGNIN_ERROR';
export const USER_LOGOUT = 'USER_LOGOUT';

export const USER_SIGNUP_LOADING = 'USER_SIGNUP_LOADING';
export const USER_SIGNUP_SUCCESS = 'USER_SIGNUP_SUCCESS';
export const USER_SIGNUP_ERROR = 'USER_SIGNUP_ERROR';

export const USER_FORGOT_LOADING = 'USER_FORGOT_LOADING';
export const USER_FORGOT_SUCCESS = 'USER_FORGOT_SUCCESS';
export const USER_FORGOT_ERROR = 'USER_FORGOT_ERROR';

export const GET_USER_DATA_LOADING = 'GET_USER_DATA_LOADING';
export const GET_USER_DATA_SUCCESS = 'GET_USER_DATA_SUCCESS';
export const GET_USER_DATA_ERROR = 'GET_USER_DATA_FORGOT_ERROR';

export const USER_UPLOADIMG_LOADING = 'USER_UPLOADIMG_LOADING';
export const USER_UPLOADIMG_SUCCESS = 'USER_UPLOADIMG_SUCCESS';
export const USER_UPLOADIMG_ERROR = 'USER_UPLOADIMG_ERROR';
